[package]
name = "gh-server"
version = "0.1.0"
authors = ["James Tranovich <jtranovich@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
juniper = "0.11"
juniper_rocket = "0.2.0"

[dependencies.rusqlite]
version = "0.17.0"
features = ["bundled"]